=== andresCodifica/soapCMC/src/main/resources/user-details.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://cmcprueba.com/users" 
xmlns:tns="http://cmcprueba.com/users" 
elementFormDefault="qualified">
	<xs:element name="GetUserDetailsRequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:int"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetUserDetailsResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="UserDetails" type="tns:UserDetails"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetAllUserDetailsRequest">
	</xs:element>
	<xs:element name="GetAllUserDetailsResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="UserDetails" type="tns:UserDetails"
							maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="UserDetails">
		<xs:sequence>
			<xs:element name="id" type="xs:int"/>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="email" type="xs:string"/>
			<xs:element name="phone" type="xs:string"/>
			<xs:element name="authentication" type="tns:Authentication"/>	
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Authentication">
		<xs:sequence>
			<xs:element name="lastDate" type="xs:string"/>
			<xs:element name="lasthour" type="xs:string"/>
			<xs:element name="attempts" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

<!-- 
<GetCourseDetailsRequest xmlns="http://cmcprueba.com/users">
	<id>123</id>
</GetUserDetailsRequest>
 -->

=== andresCodifica/soapCMC/example-files/Response.xml
<?xml version="1.0" encoding="UTF-8"?>
<GetUserDetailsResponse xmlns="http://cmcprueba.com/users"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://cmcprueba.com/users user-details.xsd">
    <UserDetails>
    	<id>123</id>
    	<name>Jhair</name>
    	<email>janska029@gmail.com</email>
    	<phone>3208216504</phone>
    	<authentication>
    		<lastDate>26/05/2020</lastDate>
    		<lasthour>15:47</lasthour>
    		<attempts>3</attempts>
    	</authentication>
    </UserDetails>
</GetUserDetailsResponse>
